name: checks
on: { workflow_dispatch, push }
env:
  PAGER: cat
  FORCE_COLOR: 1
jobs:
  check:
    strategy:
      matrix:
        include:
          - flake: nixosConfigurations.{base,postgresql}
            expect: systemd.services.postgresql.enable
          - flake: nixosConfigurations.{base,home-manager}
            expect: home-manager.users.foo.home.activationPackage
          - flake: homeConfigurations.{base,git}
            expect: xdg.configFile."git/config".enable
          - flake: darwinConfigurations.{base,dnsmasq}
            expect: launchd.daemons.dnsmasq.serviceConfig.Label
          - flake: nixvimConfigurations.{base,ty}
            expect: vim.lsp.enable("ty")

          - flake: nixosConfigurations.base --new-module '{ programs.zsh.enable = true; }'
            expect: environment.etc.zinputrc.enable
          - flake: nixosConfigurations.base -- --override-input new/nixpkgs nixpkgs/nixos-unstable-small
            expect: system.nixos.releaseFAIL

          - flake: nixosConfigurations.{base,postgresql}
            expect: systemd.services.postgresql.enable
            os: macos-latest

          - impure: nixos/configuration.nix --new-module '{ services.postgresql.enable = true; }'
          - impure: nixos/configuration.nix --new-include nixpkgs=https://channels.nixos.org/nixos-unstable-small/nixexprs.tar.xz
          - impure: nix-darwin/configuration.nix --new-module '{ services.dnsmasq.enable = true; }'
          - impure: home-manager/home.nix --new-module '{ programs.git.enable = true; }'

          - run: nix run . .#nixosConfigurations.{base,hello}
          - run: nix run github:kwbauson/configdiff github:kwbauson/configdiff?dir=test#nixosConfigurations.{base,postgresql}

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
      - if: ${{ !matrix.run }}
        run: nix build .#ci-env && echo ./result/bin >> $GITHUB_PATH
      - if: ${{ matrix.flake }}
        run: configdiff --dump dump.txt .?dir=test#${{ matrix.flake }}
      - if: ${{ matrix.impure }}
        run: configdiff --dump dump.txt test/${{ matrix.impure }}
      - if: ${{ !matrix.run }}
        run: configdiff --use-dump dump.txt | rg --color=never --passthru --fixed-strings '${{ matrix.expect }}'
      - if: ${{ matrix.run }}
        run: ${{ matrix.run }}

# TODO test the actual output
