name: checks
on: { workflow_dispatch, push }
env:
  PAGER: cat
  FORCE_COLOR: 1
jobs:
  check:
    strategy:
      matrix:
        include:
          - flake: nixosConfigurations.{base,postgresql}
          - flake: nixosConfigurations.{base,home-manager}
          - flake: homeConfigurations.{base,git}
          - flake: darwinConfigurations.{base,dnsmasq}
          - flake: nixvimConfigurations.{base,ty}

          - flake: nixosConfigurations.base --new-module '{ programs.git.enable = true; }'
          - flake: nixosConfigurations.base -- --override-input new/nixpkgs nixpkgs/nixos-unstable-small

          - flake: nixosConfigurations.{base,postgresql}
            os: macos-latest

          - impure: nixos/configuration.nix --new-module '{ services.postgresql.enable = true; }'
          - impure: nixos/configuration.nix --new-include nixpkgs=https://channels.nixos.org/nixos-unstable-small/nixexprs.tar.xz
          - impure: nix-darwin/configuration.nix --new-module '{ services.dnsmasq.enable = true; }'
          - impure: home-manager/home.nix --new-module '{ programs.git.enable = true; }'

          - run: nix run . .#nixosConfigurations.{base,hello}
          - run: nix run github:kwbauson/configdiff github:kwbauson/configdiff?dir=test#nixosConfigurations.{base,postgresql}

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
      - if: ${{ !matrix.run }}
        run: |
          nix build
          echo ./result/bin >> $GITHUB_PATH
      - if: ${{ matrix.flake }}
        run: configdiff --dump dump.txt .?dir=test#${{ matrix.flake }}
      - if: ${{ matrix.impure }}
        run: configdiff --dump dump.txt test/${{ matrix.impure }}
      - if: ${{ !matrix.run }}
        run: configdiff --use-dump dump.txt
      - if: ${{ matrix.run }}
        run: ${{ matrix.run }}

# TODO test the actual output
